[mainpage]
title = "TriFinger Cameras"
auto_general_docs = false

[intersphinx.mapping]
trifinger_docs = "https://open-dynamic-robot-initiative.github.io/trifinger_docs"
robot_fingers = "https://open-dynamic-robot-initiative.github.io/robot_fingers"
